#!/usr/bin/env python


"""Script to generate a codebook from the VCTK speech dataset.
"""


import os

from scipy.io import savemat

from multimodal.local import CONFIG
from multimodal.db.vctk import build_vctk_codebook
from multimodal.features.hac import MFCC_PARAMS


CODEBOOK_PATH = os.path.join(CONFIG['feat-dir'], "vctk_codebook.mat")
KS = [150, 150, 100]


codebooks = build_vctk_codebook(KS)
savemat(CODEBOOK_PATH, {'codebooks': codebooks,
                        'mfcc_params': MFCC_PARAMS})
