#!/usr/bin/env python2


import sys
import os
sys.path.append(os.path.abspath(os.path.join(__file__, '../../../..')))

from multimodal.db.choreo2 import build_features


build_features(force=False, verbose=True)
