#!/usr/bin/env python2


"""Script to generate a codebook from the VCTK speech dataset.
"""


import os

from scipy.io import savemat

from multimodal.local import CONFIG
from multimodal.db.vctk import load
from multimodal.features.hac import (build_codebooks_from_list_of_wav,
                                     MFCC_PARAMS)


CODEBOOK_PATH = os.path.join(CONFIG['feat-dir'], "vctk_codebook.mat")
KS = [150, 150, 100]


db = load()
codebooks = build_codebooks_from_list_of_wav(
    [r.get_audio_path() for r in db.all_records()],
    KS)
savemat(CODEBOOK_PATH, {'codebooks': codebooks,
                        'mfcc_params': MFCC_PARAMS})
