#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.abspath(os.path.join(__file__, '../../../..')))

from multimodal.db.choreo2 import download_with_features as dl_choreo2
from multimodal.db.acorns import download_meta_and_features as dl_acorns
from multimodal.db.objects import download_meta_and_features as dl_objects


dl_choreo2(overwrite=True)
dl_acorns(1, overwrite=True)
dl_objects(overwrite=True)
